### ISSUE TITLE
Installing freedombox packages

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/freedombox#12]
Why are you using these:
https://github.com/docker-scripts/freedombox/blob/master/Dockerfile#L26-L54

I thought that `apt -y install freedombox-setup` was enough for installing everything related to freedombox, isn't it?

**Comment by dashohoxha** [comment]
Again, I don't understand this:
https://github.com/docker-scripts/freedombox/blob/master/scripts/install-plinth.sh
I thought that `/usr/lib/freedombox/setup` was enough for the basic configuration of freedombox.

**Comment by dashohoxha** [comment]
Are you trying to install the development environment of FreedomBox?

If so, probably you should add a `$DEV` setting on `settings.sh`, and when this is true you install the development environment, otherwise you do the normal production installation.

Another solution is to create the branch `dev` on the repository, which does the installation of the development environment, while the branch `master` does the normal production installation.

**Comment by RadZaeem** [comment]
There are too many errors are encountered if I try to install with `apt install -y freedombox-setup`. Some errors related to Docker, while the package have pre and post scripts assuming proper Debian installation (https://salsa.debian.org/freedombox-team/freedombox-setup)

Also I need to edit plinth.config before doing first run to support wsproxy. Install with apt skips that step.

Example errors if I use apt install
```
invoke-rc.d: policy-rc.d denied execution of force-reload.
Created symlink /etc/systemd/system/dbus-org.freedesktop.Avahi.service → /lib/systemd/system/avahi-daemon.service.
Created symlink /etc/systemd/system/multi-user.target.wants/avahi-daemon.service → /lib/systemd/system/avahi-daemon.service.
Created symlink /etc/systemd/system/sockets.target.wants/avahi-daemon.socket → /lib/systemd/system/avahi-daemon.socket.
invoke-rc.d: policy-rc.d denied execution of start.
Setting up avahi-utils (0.7-3.1) ...
Setting up plinth (0.28.0) ...
Created symlink /etc/systemd/system/multi-user.target.wants/plinth.service → /lib/systemd/system/plinth.service.
/usr/sbin/policy-rc.d returned 101, not running 'start plinth.service'


```

That is why I use the version from salsa (https://salsa.debian.org/freedombox-team/plinth).

Maybe I will try again using `apt install` and see how I can fix/suppress the errors
UPDATE:
If I do `apt install freedombox-setup` I got the same error as in #8. The error _vanish_ if I do `ds restart`, stop plinth with `pkill`, edit plinth.config as in #4 and rerun plinth. In my opinion it is better to use the latest version from salsa since we have more control on the install flow to accomodate Docker's limitations.

@SunilMohanAdapa can I ask your opinion on this? Thanks in advance.

**Comment by dashohoxha** [comment]
> There are too many errors are encountered if I try to install with `apt install -y freedombox-setup`

Maybe it is because you are using `debian:buster` instead of `debian:stretch`. That package is tested on `debian:stretch`.

> That is why I use the version from salsa (https://salsa.debian.org/freedombox-team/plinth).

I suggest that you use this version of plinth: https://github.com/docker-scripts/plinth
which is actually a clone of that in salsa. The reason is that I can control the workflow of development on this one, but the one on salsa is out of my control. When the summer of code is finished we will merge your changes to salsa (assuming that you have done something useful).

> If I do apt install freedombox-setup I got the same error as in #8. The error vanish if I do ds restart, stop plinth with pkill, edit plinth.config as in #4 and rerun plinth. In my opinion it is better to use the latest version from salsa since we have more control on the install flow to accomodate Docker's limitations.

No, it is better to do both of them: a stable container and a development container.
And those are not Docker limitations. I already explained the reason of that error, it is a django limitation. It makes me a bit angry that you don't read carefully what I write and I have to repeat things several times.

> @SunilMohanAdapa can I ask your opinion on this?

Maybe you will get some help from Sunil when you start working with Plinth. For the containerization part it is me who is responsible. You should build two containers, one for the stable version of debian and freedombox, and one for the development version, where you are also going to work and make your changes.
