### ISSUE TITLE
Containerize freedombox

### ISSUE THREAD

**Issue by RadZaeem** [docker-scripts/freedombox#3]
Freedombox is yet to be containerized.

For the latest Freedombox, the Freedombox team has moved the code for Freedombox Web UI to plinth repo
https://salsa.debian.org/freedombox-team/plinth
 
freedombox-setup repo now is mostly for linking and packaging plinth as official `freedombox-setup` Debian package. No Python Django code for Freedombox Web UI here.
https://salsa.debian.org/freedombox-team/freedombox-setup

This is important to note as,
for Debian testing and above,
I have confirmed that it is possible to install Freedombox by `apt install plinth` _without_ installing Freedombox via `apt install freedombox-setup` package.

**Comment by dashohoxha** [comment]
From the other issue (#4) it seems that you have already started with this. You can start a PR, and then continue adding commits to it until the problems are solved.
When you start a PR I can see what you are doing and maybe make any suggestions.

**Comment by RadZaeem** [comment]
Docker scripts for freedombox now is usable (install and use apps)
But cannot pass some diagnostics tests 
Probably due to wsproxy settings? Or Docker container  network settings?

Failed tests:
ipv6 related
![image](https://user-images.githubusercontent.com/4066712/39475099-ed327f60-4d91-11e8-97e1-fe0a3a3341af.png)

**Comment by dashohoxha** [comment]
> Docker scripts for freedombox now is usable (install and use apps)
But cannot pass some diagnostics tests
Probably due to wsproxy settings? Or Docker container network settings?

Docker containers usually are restricted. One of the restrictions is that you cannot make changes on the network stack. Probably this affects any IPv6 configurations inside the container. It certainly affects any firewall configurations (is not allowed to use `iptables` etc.)

These restrictions can be overcome if we give the container the capability **NET_ADMIN**, like this: https://github.com/docker-scripts/bind9/blob/master/cmd/create.sh#L15 But this gives the container full access to the network stack of the host as well.

I don't know if these IPv6 features (or the firewall configuration) is important for the container, since the container is already running inside the host, behind **wsproxy** and behind the Docker daemon, and does not have direct access to the network.

Since the stable version (at least) is already running, somebody experienced with FreedomBox should give it a try and see if something is missing or needs to be fixed.

P.S: Is it possible to synchronize the issues on GitHub and those on GitLab (Salsa)? So that when I post a comment or something here it appears there as well, and the interested people are notified?
